export const ADD_COORDINATE = "ADD_COORDINATE";
export const DEL_TASK_FROM_REDUCER = "DEL_TASK_FROM_REDUCER";
export const ADD_TASK_TO_REDUCER = "ADD_TASK_TO_REDUCER";
export const ADD_TASK_TO_USER_REDUCER = "ADD_TASK_TO_USER_REDUCER";
export const DEL_TASK_FROM_USER_REDUCER = "DEL_TASK_FROM_USER_REDUCER";
export const MAKE_TASK_PENDING = "MAKE_TASK_PENDING";

export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'